image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  IMAGE_NAME_HUGO: $CI_REGISTRY_IMAGE/hugo
  IMAGE_NAME_HUGO_EXTENDED: $CI_REGISTRY_IMAGE/hugo_extended

services:
  - docker:dind

stages:
  - test
  - deploy

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

test:
  stage: test
  script:
    - TESTS="wget -qO- https://fedoraproject.org/static/hotspot.txt | grep OK && cd /git && hugo"
    - docker build --build-arg HUGO=hugo -t $IMAGE_NAME_HUGO .
    - docker build --build-arg HUGO=hugo_extended -t $IMAGE_NAME_HUGO_EXTENDED .
    - docker run -v `pwd`:/git $IMAGE_NAME_HUGO /bin/sh -c "$TESTS"
    - docker run -v `pwd`:/git $IMAGE_NAME_HUGO_EXTENDED /bin/sh -c "$TESTS"
  except:
    - schedules

deploy:
  stage: deploy
  script:
    - docker build --build-arg HUGO=hugo -t $IMAGE_NAME_HUGO .
    - docker build --build-arg HUGO=hugo_extended -t $IMAGE_NAME_HUGO_EXTENDED .
    - docker tag $IMAGE_NAME_HUGO $IMAGE_NAME
    - docker tag $IMAGE_NAME_HUGO $IMAGE_NAME:$CI_COMMIT_REF_NAME
    - docker tag $IMAGE_NAME_HUGO $IMAGE_NAME_HUGO:$CI_COMMIT_REF_NAME
    - docker tag $IMAGE_NAME_HUGO_EXTENDED $IMAGE_NAME_HUGO_EXTENDED:$CI_COMMIT_REF_NAME
    - docker push $IMAGE_NAME
    - docker push $IMAGE_NAME:$CI_COMMIT_REF_NAME
    - docker push $IMAGE_NAME_HUGO
    - docker push $IMAGE_NAME_HUGO:$CI_COMMIT_REF_NAME
    - docker push $IMAGE_NAME_HUGO_EXTENDED
    - docker push $IMAGE_NAME_HUGO_EXTENDED:$CI_COMMIT_REF_NAME
  only:
    - tags

update:
  image: python:3.6
  before_script: []
  services: []
  script:
    - pip install requests
    - ./update.py $API_TOKEN $CI_PROJECT_PATH
  only:
    - schedules
